networks:
  phpinfo-network:
    internal: true
  volume-init-network:
    internal: false

services:
  phpinfo-service:
    command:
      - -f
      - index.php
      - -S
      - 0.0.0.0:8080
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 2
    entrypoint: /usr/bin/php
    environment:
      HELLO: world
      AUTHOR: Atul
    image: ${GITHUB_USERNAME}/${GITHUB_PROJECT}:${GITHUB_RELEASE}
    networks:
      - phpinfo-network
    ports:
      - 80:8080
    user: nobody
    volumes:
      - phpinfo-volume:/shared/:ro
    working_dir: /shared/${GITHUB_PROJECT}/${GITHUB_SRC}/
  volume-init-service:
    command:
      - -c
      - rm -rf phpinfo && git clone https://github.com/${GITHUB_USERNAME}/${GITHUB_PROJECT} && cd phpinfo/ && sleep 1000 
    deploy:
      mode: global      
      placement:
        constraints:
          - node.role == worker              
    entrypoint: /bin/sh
    env_file:
      - ./${ENV_FILE}
    environment:
      HELLO: bye
    image: alpine/git:latest
    networks: 
      - volume-init-network
    user: root
    volumes:
      - phpinfo-volume:/shared/:rw
    working_dir: /shared/    

version: '3.8'

volumes:
  phpinfo-volume:
